### ISSUE TITLE
Твой код должен отображать суть 

### ISSUE THREAD

**Issue by Red-Cat-Fat** [negrime/CommandGame#7]
В данном случае код будет работать, но вне контекста enemy выглядит как bool, но ведь это не так!
Вполне корректно было бы использовать проверку вида `if(enemy!=null)` так сразу понятно, что enemy - это некий класс, а не bool переменная.
Повторюсь, что в данном контексте вроде норм, но на больших проектах это может ввести в заблуждение другого программиста.
https://github.com/negrime/CommandGame/blob/66f659ce5862942a4710dfe722829580715a23d1/Assets/Scripts/Gameplay/BaseMinion.cs#L95-L96

**Comment by negrime** [comment]
https://github.com/negrime/CommandGame/commit/5e0f559067145850e1e77f296f063fe2d0be0bca

**Comment by Red-Cat-Fat** [comment]
Это касается не только конкретной строки. По коду встречал подобные проверки. Просто имей это ввиду, что так делать не стоит

**Comment by negrime** [comment]
Понял, спасибо!
